// Generated by CoffeeScript 1.10.0
(function() {
  window.Complex = (function() {
    function Complex(re, im1) {
      this.re = re;
      this.im = im1;
    }

    Complex.prototype.conjugate = function() {
      var im;
      im = -im;
    };

    Complex.prototype.add = function(c) {
      this.re += c.re;
      this.im += c.im;
    };

    Complex.prototype.multiply = function(c) {
      var ti, tr;
      tr = this.re * c.re - this.im * c.im;
      ti = this.re * c.im + this.im * c.re;
      this.re = tr;
      this.im = ti;
    };

    Complex.prototype.divide = function(c) {
      var ti, tmp, tr;
      tr = this.re * c.re + this.im * c.im;
      ti = this.im * c.re - this.re * c.im;
      tmp = c.re * c.re + c.im * c.im;
      this.re = tr / tmp;
      return this.im = ti / tmp;
    };

    Complex.prototype.minus = function() {
      this.re = -this.re;
      this.im = -this.im;
    };

    Complex.prototype.abs = function() {
      return Math.sqrt(this.re * this.re + this.im * this.im);
    };

    return Complex;

  })();

}).call(this);
